import "@fontsource/bebas-neue/400.css";
import type { Site } from "./lib";

export const SITE: Site = {
  name: "The Hungry Man",
  sub: { en: "Shawarma, kebabs & dimsums · Rodeo Drive, South City II", hi: "शवर्मा, कबाब और डिमसम · रोडियो ड्राइव, साउथ सिटी II" },
  banner: { en: "Hungry at 2am? They're open 24 hours", hi: "रात 2 बजे भूख लगी? 24 घंटे खुला है" },
  phone: "919873293955",
  phoneDisplay: "+91 98732 93955",
  lat: 28.4198198,
  lon: 77.0517633,
  hours: [[0, 24], [0, 24], [0, 24], [0, 24], [0, 24], [0, 24], [0, 24]],
  price: { en: "₹200–400 per person", hi: "₹200–400 प्रति व्यक्ति" },
  theme: {
    dark: true,
    bg: "#0e0c0a",
    bg2: "#161310",
    panel: "#1c1814",
    ink: "#f7f1e6",
    ink2: "#cfc5b4",
    ink3: "#8e8473",
    line: "#2f2a22",
    accent: "#ffcf2e",
    onAccent: "#241a00",
    display: "Bebas Neue",
    weight: 400,
    upper: true,
  },
  scene: "feast",
  align: "left",
  hero: {
    title: [
      { en: "Juicy shawarma,", hi: "रसीला शवर्मा," },
      { en: "open all night.", hi: "पूरी रात खुला।" },
    ],
    proof: {
      en: "4.5 on Google from 786 reviews. Shawarma, kurkure shawarma, kebab strips and six dips, 24 hours a day on Rodeo Drive, South City II.",
      hi: "गूगल पर 786 रिव्यू से 4.5। शवर्मा, कुरकुरे शवर्मा, कबाब स्ट्रिप्स और छह डिप्स, 24 घंटे, रोडियो ड्राइव, साउथ सिटी II।",
    },
    fallback: "/img/p11.jpg",
  },
  marquee: ["Chicken Shawarma", "Kurkure Shawarma", "Piri Piri", "Chicken Lollipop", "Dimsums", "Mutton Kebab Strips", "Six Dips"],
  dishes: {
    title: { en: "What Gurgaon orders here", hi: "गुड़गांव यहां क्या मंगाता है" },
    body: { en: "Every line is a real Google review.", hi: "हर लाइन असली गूगल रिव्यू है।" },
    layout: "cards",
    items: [
      { name: { en: "Shawarma", hi: "शवर्मा" }, quote: "Ordered one plate and trust me it’s the juiciest and tastiest shawarma I have tried after a long time.", img: "/img/p11.jpg" },
      { name: { en: "Kurkure Shawarma", hi: "कुरकुरे शवर्मा" }, quote: "the Kurkure Shawarmas take it up a notch—crispy, crunchy, and perfectly spiced with Piri Piri masala.", img: "/img/p13.jpg" },
      { name: { en: "The Dips", hi: "डिप्स" }, quote: "I got a total of six dips, all the dips were great in taste", img: "/img/p12.jpg" },
      { name: { en: "Lollipop & Dimsums", hi: "लॉलीपॉप और डिमसम" }, quote: "Chicken lolipop - 9/10 Chicken dimsums ( size 3x h regular momos se ) - 8/10" },
      { name: { en: "Mutton Kebab Strips", hi: "मटन कबाब स्ट्रिप्स" }, quote: "Tried mutton kebab strips, it was first class.." },
    ],
  },
  gallery: { title: { en: "", hi: "" }, layout: "strip", photos: [] },
  feature: {
    kind: "daynight",
    title: { en: "Day or 2am, same shawarma", hi: "दिन हो या रात 2 बजे, वही शवर्मा" },
    body: { en: "Open around the clock.", hi: "चौबीसों घंटे खुला।" },
    day: {
      label: { en: "By day", hi: "दिन में" },
      body: { en: "Eat in, or in your car out front.", hi: "अंदर बैठकर, या बाहर अपनी कार में।" },
      img: "/img/p1.jpg",
      quote: "you can eat in the restaurant or in your car parked in front. Do visit them if you are shawarma lover.",
    },
    night: {
      label: { en: "At 2am", hi: "रात 2 बजे" },
      body: { en: "Delivered while the city sleeps.", hi: "जब शहर सोता है, तब डिलीवरी।" },
      img: "/img/p8.jpg",
      quote: "Perfect 2am delivery. Loved the quality and taste! Thankyou!",
    },
  },
  reviews: {
    title: { en: "678 of 786 reviews are five stars", hi: "786 में से 678 रिव्यू पांच स्टार" },
    rating: 4.5,
    dist: [678, 16, 8, 10, 74],
    quotes: [
      { quote: "Best shawarma in Gurgaon.  M regular here must try their shawarma", stars: 5 },
      { quote: "Good place to grab a sumptuous shwarma in neighbourhood. Shwarma was delicious with generous filling.", stars: 5 },
      { quote: "they are famous for shawarma . i tried almost every thing no one can beat the quality of their any food items must try", stars: 5 },
    ],
  },
  visit: {
    title: { en: "On Rodeo Drive, South City II", hi: "रोडियो ड्राइव, साउथ सिटी II" },
    img: "/img/p1.jpg",
    alt: "The Hungry Man storefront",
    address: { en: "DG 09, Rodeo Drive, Arcadia-II, South City II, Sector 49, Gurugram", hi: "DG 09, रोडियो ड्राइव, आर्केडिया-II, साउथ सिटी II, सेक्टर 49, गुरुग्राम" },
    note: { en: "Open 24 hours, every day.", hi: "हर दिन 24 घंटे खुला।" },
  },
  pour: { from: "pan", into: "kadhai", liquid: "#e8742c", foam: "#f5a050", thick: 1.6, hot: true },
  story: [
    { kicker: { en: "The shawarma", hi: "शवर्मा" }, title: { en: "The juiciest in a long time.", hi: "बहुत समय बाद इतना रसीला।" }, quote: "Ordered one plate and trust me it’s the juiciest and tastiest shawarma I have tried after a long time." },
    { kicker: { en: "The crunch", hi: "क्रंच" }, title: { en: "Kurkure, with piri piri.", hi: "कुरकुरा, पिरी पिरी के साथ।" }, quote: "the Kurkure Shawarmas take it up a notch—crispy, crunchy, and perfectly spiced with Piri Piri masala." },
    { kicker: { en: "The hour", hi: "समय" }, title: { en: "Even at 2am.", hi: "रात 2 बजे भी।" }, quote: "Perfect 2am delivery. Loved the quality and taste! Thankyou!" },
  ],
  build: {
    title: { en: "Build your order in a few taps", hi: "कुछ टैप में अपना ऑर्डर बनाइए" },
    body: { en: "Tap what you want, set how many and when. It goes to WhatsApp exactly as you see it.", hi: "जो चाहिए टैप करें, कितने लोग और कब, चुनें। मैसेज व्हाट्सऐप पर ठीक ऐसे ही जाएगा।" },
    pick: { label: { en: "Order", hi: "ऑर्डर" }, options: [
      { name: { en: "Delivery", hi: "डिलीवरी" } },
      { name: { en: "Pickup", hi: "पिकअप" } },
      { name: { en: "Eat in the car", hi: "कार में खाना" } },
    ] },
    items: [
      { en: "Chicken Shawarma", hi: "चिकन शवर्मा" },
      { en: "Kurkure Shawarma", hi: "कुरकुरे शवर्मा" },
      { en: "Chicken Lollipop", hi: "चिकन लॉलीपॉप" },
      { en: "Chicken Dimsums", hi: "चिकन डिमसम" },
      { en: "Mutton Kebab Strips", hi: "मटन कबाब स्ट्रिप्स" },
    ],
    people: true,
    when: true,
    hello: { en: "Hi The Hungry Man, I'd like:", hi: "नमस्ते द हंग्री मैन, मुझे चाहिए:" },
  },
  waHello: {
    en: "Hi The Hungry Man, I'd like to order. Items: , delivery / pickup: , address: ",
    hi: "नमस्ते द हंग्री मैन, मुझे ऑर्डर देना है। आइटम: , डिलीवरी / पिकअप: , पता: ",
  },
  order: ["build", "dishes", "feature", "reviews", "visit"],
};
